### PR TITLE
temperature converter

### PR DESCRIPTION
**Pull request by Mannu292001**
temperature converter using html,css,javascript

### CODE REVIEW

**Comment by Mannu292001** [comment]
plz consider my file

**Comment by Meghwantsingh** [comment]
I will view it later currently busy with job hunting exam.

**Comment by Meghwantsingh** [comment]
Also make ka readme file ur add inside the folder which contain project screenshot and short description .
Great work i will merge it.

**Comment by Mannu292001** [comment]
thank u sir

**Comment by Mannu292001** [comment]
plz add hacktoberfest 2022 tag

**Pull request merged**
