### PR TITLE
Create patterns

### PR DESCRIPTION
**Pull request by aman6969**

### CODE REVIEW

**Comment by Meghwantsingh** [comment]
you should add only 1 pattern at a time Save time with proper commented code. Do changes I will check. And merge.

**Comment by aman6969** [comment]
ok thank you i am doing it @Meghwantsingh

**Comment by aman6969** [comment]
i have changed now please check and merge @Meghwantsingh

**Comment by Meghwantsingh** [comment]
What changes you have done Aman ?

**Comment by aman6969** [comment]
i have changed the code into go lang. @Meghwantsingh

**Comment by aman6969** [comment]
> you should add only 1 pattern at a time Save time with proper commented code. Do changes I will check. And merge. and mark star to repo it will help us. good luck and good day.

this changes that you have told @Meghwantsingh

**Pull request merged**
